# 应用服务 WEB 访问端口
server:
  port: 8080

# 数据库的四大连接参数
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tlias
    username: root
    password: root

# mybatis的配置
mybatis:
  mapper-locations: classpath:mapper/*.xml  # 扫描mapper文件夹下的所有xml文件
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启 mybatis 的日志
    map-underscore-to-camel-case: true  # 开启驼峰命名映射    xxx_xxx  --->   xxxXxx    max_value -->  maxValue
